// Writes dist/sw.js: the service worker that makes EMWS install and work offline.
//
// Hand-written on purpose (no workbox, no plugin): the whole job is "precache every file
// the build produced, serve them cache-first, and fetch fresh HTML when online". The
// asset list and a content digest are baked in here AFTER vite has built, so the worker's
// cache name changes exactly when any shipped byte does.
//
// Deliberately NOT cached: the PHP endpoints (solver/, community/ - live services),
// web.config (IIS's, not the browser's), and source maps (large, and only DevTools asks).

import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, relative, sep } from 'node:path';

const dist = fileURLToPath(new URL('../dist/', import.meta.url));

const SKIP = /\.(php|map)$|(^|[\\/])web\.config$|(^|[\\/])sw\.js$/i;

function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return out; // a locked leftover (dist/.review-temp) is not part of the build
  }
  for (const entry of entries) {
    if (entry.name.startsWith('.')) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (!SKIP.test(full)) out.push(full);
  }
  return out;
}

const files = walk(dist).sort();
if (!files.some((f) => f.endsWith('index.html'))) {
  console.error('build-sw: dist/index.html is missing - run the build first.');
  process.exit(1);
}

const hash = createHash('sha256');
const assets = [];
for (const file of files) {
  hash.update(relative(dist, file));
  try {
    hash.update(readFileSync(file));
  } catch {
    continue; // unreadable: leave it out of the cache rather than fail the install
  }
  assets.push('./' + relative(dist, file).split(sep).join('/'));
}
const digest = hash.digest('hex').slice(0, 12);

// The two engine builds. EMWS's rule is that a visitor downloads only the engine their
// browser will run (the default smoke enforces it), so they are split out here and the
// worker caches one pair. The patterns are length-exact on Vite's 8-character hash, so a
// plain build whose hash happened to begin "simd-" could not be mistaken for the other.
const PLAIN = /^\.\/assets\/nec2c-[A-Za-z0-9_-]{8}\.(js|wasm)$/;
const SIMD = /^\.\/assets\/nec2c-simd-[A-Za-z0-9_-]{8}\.(js|wasm)$/;
const plain = assets.filter((a) => PLAIN.test(a));
const simd = assets.filter((a) => SIMD.test(a));
const common = assets.filter((a) => !PLAIN.test(a) && !SIMD.test(a));
for (const [name, pair] of [['plain', plain], ['SIMD', simd]]) {
  if (pair.length !== 2 || !pair.some((a) => a.endsWith('.js')) || !pair.some((a) => a.endsWith('.wasm'))) {
    console.error(`build-sw: expected the ${name} engine as one .js and one .wasm, found ${JSON.stringify(pair)}. Did the engine files get renamed?`);
    process.exit(1);
  }
}

const sw = `// Generated by scripts/build-sw.mjs - do not edit; it is rewritten on every build.
// Public domain (The Unlicense). By ZR1JT.
const CACHE = 'emws-${digest}';
const COMMON = ${JSON.stringify(['./', ...common], null, 0)};
const ENGINE_PLAIN = ${JSON.stringify(plain)};
const ENGINE_SIMD = ${JSON.stringify(simd)};

// The same question src/engine/nec2/run.ts asks before choosing an engine: does this
// runtime validate i8x16.splat? Asked here so only the engine the page will run is cached.
function supportsWasmSimd() {
  try {
    return WebAssembly.validate(new Uint8Array([
      0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00, 0x01, 0x04, 0x01, 0x60, 0x00, 0x00, 0x03, 0x02, 0x01, 0x00,
      0x0a, 0x09, 0x01, 0x07, 0x00, 0x41, 0x00, 0xfd, 0x0f, 0x1a, 0x0b,
    ]));
  } catch {
    return false;
  }
}

self.addEventListener('install', (e) => {
  const assets = [...COMMON, ...(supportsWasmSimd() ? ENGINE_SIMD : ENGINE_PLAIN)];
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(assets)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const { request } = e;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;
  // The solver proxy and the community store are live services, never cached.
  if (url.pathname.includes('/solver/') || url.pathname.includes('/community/')) return;
  if (request.mode === 'navigate') {
    // Fresh HTML when online, so a deploy shows up on the next reload; the shell offline.
    e.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((c) => c.put('./', copy)).catch(() => {});
          return response;
        })
        .catch(() => caches.match('./')),
    );
    return;
  }
  e.respondWith(caches.match(request).then((hit) => hit ?? fetch(request)));
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
const kb = files.reduce((n, f) => n + statSync(f).size, 0) / 1024;
console.log(`build-sw: ${common.length + 1} shared files + one engine pair of two precached (${kb.toFixed(0)} kB on disk, both engines), cache emws-${digest}`);
